### ISSUE TITLE
Feature feedback: extension setup

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [100Automations/github-story-points-calculator#18]
### Overview
As a product manager I want to setup the story points calculator extension without having to read instructions

### Details
When I go to install it, it has this complicated set of instructions instead of a single button.  See resources for suggested new functionality.  Until it can do other filters, it shouldn't contain the capability to add new filters, but rather be focused on making it easy to know what to do, so that instructions are barely necessary

### Action Items
- [ ] Review the image below
- [ ] discuss potential problems if necessary to get more feedback
- [ ] implement if no objections

### Resources/Instructions
![image](https://user-images.githubusercontent.com/37763229/172969663-aee112ef-add7-4e8c-a7bf-dd8062a077f1.png)

**Comment by ExperimentsInHonesty** [comment]
@Aveline-art @henlatourrette please see new mockups here, the screens are in order (indicated by numbers) and represent different states.  If you click in a new field and start typing the radio box changes to the new automatically.

[GitHub Story Points mock ups](https://docs.google.com/presentation/d/1BUjCcp-E9SNZ41pO1kHCBXxp2R1tnN_DNWIO2aPf76Q/edit#slide=id.g1334826efd5_0_61)

**Comment by ExperimentsInHonesty** [comment]
@Aveline-art and @henlatourrette I updated it a bit, check it again [GitHub Story Points mock ups](https://docs.google.com/presentation/d/1BUjCcp-E9SNZ41pO1kHCBXxp2R1tnN_DNWIO2aPf76Q/edit#slide=id.g1334826efd5_0_61)

**Comment by Aveline-art** [comment]
@ExperimentsInHonesty Looks good! Let me know when you have a final draft, then I can port this over.

**Comment by henlatourrette** [comment]
@Aveline-art @ExperimentsInHonesty , I think we should go with this final draft for the moment.

We're trying to bring in a UI Designer to help us with the final touches but that could take more time and we could update it in a next version.
